name: Build VSIX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: NPM init
      run: npm install
  
    - name: VSCE build
      run: npm run ci:package

    - name: VSIX upload
      uses: actions/upload-artifact@v4.2.0
      with:
        name: vsix
        path: bugmark.vsix
        retention-days: 3


