name: Build VSIX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 'lts'
        cache: 'npm'
  
    - name: Build VSIX
      run: npm run ci:package

    - name: Upload VSIX as Artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        name: "*.vsix"
        retention-days: 3


