name: Publish VSIX

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: NPM init
      run: npm install
  
    - name: VSCE publish
      run: npm run ci:publish



