name: Publish VSIX

on:
  push:
    branches: [ "master" ]
    paths:
    - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: NPM init
      run: npm install

    - name: VSCE publish
      run: npm run ci:publish
      env:
        BUGMARK_PAT: ${{ secrets.BUGMARK_PAT }}



